[project]
name = "refactoring-kata-lift-pass-pricing"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "flask>=3.1.1",
    "pymysql>=1.1.1",
    "pytest>=8.3.5",
    "requests>=2.32.3",
]
