name: php-simple-build

on:
  push:
    paths:
      - 'php-simple/**'
      - '.github/workflows/php-simple-build.yml'
  pull_request:
    paths:
      - 'php-simple/**'
      - '.github/workflows/php-simple-build.yml'

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      DB_USER: root
      DB_OLD_PASSWORD: root
      DB_PASSWORD: mysql
      
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Start MYSQL and import DB
      run: |
        sudo systemctl start mysql
        mysqladmin --user=${{ env.DB_USER }} --password=${{ env.DB_OLD_PASSWORD }} password ${{ env.DB_PASSWORD }}
        mysql -u${{ env.DB_USER }} -p${{ env.DB_PASSWORD }} < ${GITHUB_WORKSPACE}/database/initDatabase.sql  

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: 7.3

    - name: Set up dependencies
      working-directory: php-simple
      run: composer install

    - name: Test
      working-directory: php-simple
      run: ./vendor/bin/phpunit
